'use client'
import React, { useState } from 'react';
import { BsFillMoonStarsFill, BsSun } from 'react-icons/bs';
import { AiFillGithub, AiFillLinkedin, AiFillYoutube } from 'react-icons/ai';
import { IoLibraryOutline } from 'react-icons/io5';
import { PiFrameCornersBold } from 'react-icons/pi';
import { FaCode } from 'react-icons/fa6';
import { SiNetlify } from 'react-icons/si';
import Link from 'next/link';
import Head from 'next/head';
import Image from 'next/image';
import web1 from '../../public/nexxt-tic.png'
import web2 from '../../public/mvp.png';
export default function Home() {
  const [darkMode, setDarkMode] = useState(true);
  const [color, setColor] = useState(3)
  const [isClicked, setClicked] = useState(false);
  const handleClick = () => {
    setClicked(!isClicked)
  }
  const handleColor = (e: any) => {
    setColor(parseInt(e.target.textContent, 10))
  }
  const colors = [
    {
      "color": "light-gray",
      "bg": `bg-gray-200`,
      "text": `text-black`,
      "card": "dark:bg-gradient-to-b dark:from-gray-100 dark:to-gray-300"
    },
    {
      "color": "orange",
      "bg": "bg-gradient-to-l from-orange-400 to-orange-600",
      "text": "text-white",
      "card": "dark:bg-gradient-to-t dark:from-[#f38701] dark:to-[#f7A400]"
    },
    // {
    //   "color": "yellow",
    //   "bg": `bg-gray-900`,
    //   "text": "text-white",
    //   "card": "dark:bg-gradient-to-t dark:from-gray-700 dark:to-gray-800"
    // },
    {
      "color": "green",
      "bg": `bg-green-800 bg-opacity-80`,
      "text": "text-white",
      "card": "dark:bg-gradient-to-t dark:from-[#79AC78] dark:to-[#b0d9b1]"
    },
    // {
    //   "color": "blue",
    //   "bg": `bg-gray-900`,
    //   "text": "text-white",
    //   "card": "dark:bg-gradient-to-t dark:from-gray-700 dark:to-gray-800"
    // },
    {
      "color": "dark-gray",
      "bg": `bg-gray-900`,
      "text": "text-white",
      "card": "dark:bg-gradient-to-t dark:from-gray-700 dark:to-gray-800"
    },
  ]
  return (
    <div className={` ${darkMode ? 'dark' : ''}`}>
      <Head>
        <title>Moe Sarraf</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={` bg-gray-200 px-10 ${darkMode ? colors[color].bg : ''} md:px-20 lg:px-40`}>
        <section className="min-h-screen">
          <nav className={`py-10 mb-12 flex justify-between ${darkMode ? colors[color].text : ''}`}>
            <h1 className={`font-burtons text-xl`}>Lilglu4e</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={handleClick}
                  className=" cursor-pointer text-2xl"
                />
                {isClicked ?
                  (
                    //ROYGBIV
                    <ul
                      className='absolute rounded mt-5 flex justify-between list-none bg-gray-500 flex-wrap px-2'
                    >
                      <li onClick={handleColor}>
                        <div className='bg-gray-200 rounded-full border-current w-8 h-8 flex items-center justify-center text-white m-1'>0</div>
                      </li>
                      <li onClick={handleColor}>
                        <div className='bg-orange-500 rounded-full border-current w-8 h-8 flex items-center justify-center text-white m-1'>1</div>
                      </li>
                      {/* <li>
                        <div className='bg-yellow-500 rounded-full border-current w-8 h-8 flex items-center justify-center text-white m-1'>2</div>
                      </li> */}
                      <li onClick={handleColor}>
                        <div className='bg-green-500 rounded-full border-current w-8 h-8 flex items-center justify-center text-white m-1'>2</div>
                      </li>
                      {/* <li>
                        <div className='bg-blue-500 rounded-full border-current w-8 h-8 flex items-center justify-center text-white m-1'>4</div>
                      </li> */}
                      <li onClick={handleColor}>
                        <div className='bg-gray-900 rounded-full border-current w-8 h-8 flex items-center justify-center text-white m-1'>3</div>
                      </li>
                    </ul>
                  ) : (
                    null
                  )}
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="https://www.linkedin.com/ambry/?x-li-ambry-ep=AQI9QtglMchyDAAAAYruv5tUbCgbE1tQ13i6m6ayLQPZUMDmo8x6YWMLHr0Y9lg7gKDoLSfFTfRJlVmmEv21r45JKNNiMYGaf9B8lbpMUN5SOlZq6v2S3MNNlAbj6ufjJXfr4px62PHnVXFso-yzwTFN0RBSNZKRKsqCDonJFb584UvH0zTajc8sDDLRK6AmF8SRXTVQnIYVBkaOTmwpBfm_9P1oBUoHsidHXNjGAr4HDNLZMdYb63R4IE8bB9YWuYSMyd2DR7cznKPz_iO758odftIgbeaLT2Ui5oeKaie5s7JBP_dqIxyxZsDqe37XbRLbtG6Ys9q3FYEHlbH8n2WXhLIgGgkmNrYFPQKTudRZBMK-JyQD7S1MkJX9Nth5FUUvo-O8FjTHQMsC13LOQio8a39Igwn7eMP6MB34xsawckK4bBcrBuwvRjnW24fs5ONJOjzJkMgaNGSRrwsySNidy1xCGlku7xClU39fS317FxRbc7QkcetJPbqb7I9lnLLA-wDSbaPP39mkwf479AhOHuB25gqdG8w10oQA19tdaloMZDKMzST6qMtuFd-O8UOdRA"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className={`text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl`}>
              Moe Sarraf
            </h2>
            <h3 className={`text-2xl py-2 ${darkMode ? (colors[color].text) : ('')} md:text-3xl`}>
              Developer and designer.
            </h3>
            <p
              className={`text-md py-5 leading-8 text-gray-800 ${darkMode ? (colors[color].text):('')} max-w-xl mx-auto md:text-xl`}            >
              {`As a Computer Science student deeply engaged with Data Science, AI, and Full-Stack Development, I am driven by a passion to blend creativity and technology. My portfolio, featuring diverse projects such as an interactive React mini-game and an innovative NBA MVP prediction model, is a testament to my commitment to crafting engaging user experiences and leveraging the power of data-driven insights.`}
            </p>
            <div className={`text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400`}>
              <Link href={'https://github.com/Lilglu4e'}><AiFillGithub /></Link>
              <Link href={'https://www.linkedin.com/in/mohammad-sarraf-3893a81b7/'}><AiFillLinkedin /></Link>
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className={`text-3xl py-1 ${darkMode ? (colors[color].text):('')} `}>Skills</h3>
            <p className={`text-md py-2 leading-8 ${darkMode ? (colors[color].text):('')}`}>
              {/* Since the beginning of my journey as a freelance designer and
							developer, I've done remote work for */}
              I bring a diverse skill set to the table, encompassing 
              <span className="text-teal-500"> brand design </span>, <span className="text-teal-500"> programming </span>, 
              and <span className="text-teal-500"> education </span>. My expertise lies not only in creating visually appealing designs 
              and efficient code but also in imparting this knowledge through teaching.
            </p>
            {/* <p className={`text-md py-2 leading-8 text-gray-800 ${darkMode ? (colors[color].text):('')}`}>
              I offer from a wide range of services, including brand design,
              programming and teaching.
            </p> */}
          </div>
          <div className="lg:flex gap-10">
            <div className={`text-center ${darkMode ? colors[color].text : ('')} shadow-lg p-10 rounded-xl my-10  ${darkMode ? colors[color].card : ('')} flex-1`}>
              <PiFrameCornersBold className={`w-16 h-16 text-teal-600 mx-auto`} />
              <h3 className="text-lg font-medium pt-8 pb-2  ">
                FrameWorks
              </h3>
              <p className="py-2">
My technical proficiency is anchored in a variety of frameworks that enhance the development process
              </p>
              {/* <h4 className="text-teal-300 py-4">#####</h4> */}
              <p className="text-inherit py-1">React</p>
              <p className="text-inherit py-1">Next.js</p>
              <p className="text-inherit py-1">Figma</p>
              <p className="text-inherit py-1">Firebase</p>
              <p className="text-inherit py-1">Material-UI, Tailwind, BootsTrap</p>
            </div>
            <div className={`text-center ${darkMode ? colors[color].text : ('')} shadow-lg p-10 rounded-xl my-10 ${darkMode ? colors[color].card : ('')}  flex-1`}>
              <IoLibraryOutline className={`w-16 h-16 text-teal-600 mx-auto`} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">
                Libraries
              </h3>
              <p className="py-2">
I leverage powerful libraries to process data, create machine learning models, and visualize results
              </p>
              {/* <h4 className="text-teal-300 py-4">#####</h4> */}
              <p className="text-inherit py-1">Pandas</p>
              <p className="text-inherit py-1">NumPy</p>
              <p className="text-inherit py-1">TensorFlow</p>
              <p className="text-inherit py-1">sci-kitlearn, matplotlib</p>
              <p className="text-inherit py-1">matplotlib</p>
            </div>
            <div className={`text-center ${darkMode ? colors[color].text : ('')} shadow-lg p-10 rounded-xl my-10 ${darkMode ? colors[color].card : ('')}  flex-1`}>
              <FaCode className={`w-16 h-16 text-teal-600 mx-auto`} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">Programming Languages</h3>
              <p className="py-2">
Proficient in multiple programming languages, enabling versatility across various projects
              </p>
              {/* <h4 className="text-teal-300 py-4">##### </h4> */}
              <p className="text-inherit py-1">C/C++</p>
              <p className="text-inherit py-1">Python</p>
              <p className="text-inherit py-1">SQL</p>
              <p className="text-inherit py-1">Java</p>
              <p className="text-inherit py-1">HTML/CSS/JavaScript</p>
            </div>
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className={`text-3xl py-1 ${darkMode ? (colors[color].text):('')}`}>Portofolio</h3>
            <p className={`text-md py-2 leading-8 text-gray-800 ${darkMode ? (colors[color].text):('')}`}>
              {`As a dedicated Computer Science student at Wilfrid Laurier University and an 
              experienced IT Systems and Automation Specialist at Caseware, I, Moe Sarraf, have 
              developed a unique blend of skills in Data Science, AI, and Full-Stack Development. 
              My portfolio showcases diverse projects, such as an NBA MVP prediction model where 
              I harnessed data analytics and machine learning, and a React-based mini-game that 
              demonstrates my proficiency in creating dynamic, user-focused applications. These 
              projects reflect not just my technical acumen but also my passion for blending creativity 
              with functionality, offering a glimpse into my journey 
              of continuous learning and innovation in the ever-evolving tech landscape.`}
              <span className="text-teal-500"> agencies </span>
              {`consulted for`} <span className="text-teal-500">startups </span>
              {`and collaborated with talanted people to create digital products
              for both business and consumer use.`}
            </p>

          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 relative group">
              <Image
                className="rounded-lg object-cover"
                layout="responsive"
                src={web1}
                alt={``}
              />
              <div className='bg-gray-500 opacity-0 group-hover:opacity-100 absolute inset-x-0 top-0 p-4 transform translate-y-full transition-opacity duration-300'>
                <div className='flex justify-between items-center'>
                  <p className='text-white ml-3 mt-3'>Tic-Tac-Toe</p>
                </div>
                <div className='flex justify-between items-center pb-1'>
                  <p className='text-white ml-3'>Next.js, React, HTML, JavaScript, CSS, Tailwind, Firebase</p>
                  <div className='flex items-center'>
                    <Link href={'https://github.com/Lilglu4e/next_tic'}><AiFillGithub className='text-white mr-3 w-6 h-6' /></Link>
                    <Link href={'https://lilglu4e-firebase.netlify.app/'}><SiNetlify className='text-white w-6 h-6 mr-3' /></Link>
                  </div>
                </div>
              </div>
            </div>
            <div className="basis-1/3 flex-1 relative group">
              <Image
                className="rounded-lg object-cover"
                layout="responsive"
                src={web2}
                alt={``}
              />
              <div className='bg-gray-500 opacity-0 group-hover:opacity-100 absolute inset-x-0 top-0 p-4 transform translate-y-full transition-opacity duration-300'>
                <div className='flex justify-between items-center'>
                  <p className='text-white ml-3 mt-3'>Nba MVP prediction Model</p>
                </div>
                <div className='flex justify-between items-center pb-1'>
                  <p className='text-white ml-3'>Jupyter, Pandas, NumPy, matplotlib.pyplot, seaborn, sklearn</p>
                  <div className='flex items-center'>
                    <Link href={'https://github.com/Lilglu4e/ML-model'}><AiFillGithub className='text-white mr-3 w-6 h-6' /></Link>
                    {/* <Link href={'https://lilglu4e-firebase.netlify.app/'}><SiNetlify className='text-white w-6 h-6 mr-3' /></Link> */}
                  </div>
                </div>
              </div>
            </div>


          </div>
        </section>
      </main>
    </div>
  );
}
