'use client'
import React, { useState } from 'react';
import { BsFillMoonStarsFill, BsSun } from 'react-icons/bs';
import { AiFillGithub, AiFillLinkedin, AiFillYoutube } from 'react-icons/ai';
import Link from 'next/link';
import Head from 'next/head';
export default function Home() {
	const [darkMode, setDarkMode] = useState(true);

	return (
		<div className={` ${darkMode ? 'dark' : ''}`}>
			<Head>
				<title>Moe Sarraf</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
				<section className="min-h-screen">
					<nav className="py-10 mb-12 flex justify-between dark:text-white">
						<h1 className="font-burtons text-xl">Lilglu4e</h1>
						<ul className="flex items-center">
							<li>
								{darkMode ? (
									<BsSun
										onClick={() => setDarkMode(!darkMode)}
										className=" cursor-pointer text-2xl"
									/>
								) : (
									<BsFillMoonStarsFill
										onClick={() => setDarkMode(!darkMode)}
										className=" cursor-pointer text-2xl"
									/>
								)}
							</li>
							<li>
								<a
									className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
									href="#"
								>
									Resume
								</a>
							</li>
						</ul>
					</nav>
					<div className="text-center p-10 py-10">
						<h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
							Moe Sarraf
						</h2>
						<h3 className="text-2xl py-2 dark:text-white md:text-3xl">
							Developer and designer.
						</h3>
						<p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
							{`I'm a computer science student passionate about Data Science, AI, 
							and Full-Stack Development. I've crafted projects like a React mini-game 
							and an NBA MVP prediction model, showcasing my skills in creating engaging 
							user experiences and harnessing data-driven insights.`}
						</p>
						<div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
							<Link href={'https://github.com/Lilglu4e'}><AiFillGithub /></Link>
							<Link href={'https://www.linkedin.com/in/mohammad-sarraf-3893a81b7/'}><AiFillLinkedin /></Link>
						</div>
					</div>
				</section>
			</main>
		</div>
	);
}
